// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace Terra
{
	public interface INoiseGenerator
	{
		float Generate1D(float x);
		float Generate2D(float x, float y);
		float Generate3D(float x, float y, float z);
	}
}

